server:
  port: 8091
spring:
  application:
    name: dl4j-ai-service
  ai.vectorstore.pgvector:
    dimensions: 100
  cloud:
    function:
      definition: dl4jWord2Vectors;
ai:
  model.word.vector.path: "/Users/Projects/PlayGround/ai-ml/deeplearning4j/dev/deeplearning4j-examples/dl4j-examples/src/runtime/data/GoogleNews-vectors-negative300.bin.gz"