spring:
  application:
    name: "web-ai-app"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresml
    username: postgres
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384
        initialize-schema: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  model:
#    uri: "http://localhost:8091/dl4jWord2Vectors"
#    word.vector.path: "/Users/Projects/PlayGround/ai-ml/deeplearning4j/dev/deeplearning4j-examples/dl4j-examples/src/runtime/data/GoogleNews-vectors-negative300.bin.gz"
  vector.similarity.search.threshold: 0.8