spring.application.name=spring-consumer
server.port=0
# Definite Spring Cloud Stream Consumer bean name
spring.cloud.function.definition=aiAgentProcessor
#Define an alias for the consumer bean
spring.cloud.stream.function.bindings.aiAgentProcessor-in-0=input
spring.cloud.stream.function.bindings.aiAgentProcessor-out-0=output
#Group the group name
spring.cloud.stream.bindings.input.group=ai-gent
#Group the destination
spring.cloud.stream.bindings.input.destination=letters
spring.cloud.stream.bindings.output.destination=letters
# Connection names
spring.cloud.stream.rabbit.binder.connection-name-prefix==${spring.application.name}
#Default a RabbitMQ stream
spring.cloud.stream.rabbit.bindings.input.consumer.containerType=STREAM
spring.cloud.stream.rabbit.bindings.input.consumer.bindingRoutingKey=${agent.author}
spring.cloud.stream.rabbit.bindings.output.producer.routingKeyExpression=payload.receiver
agent.author=judy
agent.replySubjectPrefix="RE:"