apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgres
    run:  postgres
  name:  postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  postgres
  template:
    metadata:
      labels:
        name:  postgres
    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
          image: ghcr.io/postgresml/postgresml:2.7.12
          command: [ "sleep" ]
          args: ["infinity"]
#          command: [ "sudo" ]
#          args: [ "-u", "postgresml", "psql", "-d", "postgresml"]
          name: postgres
          imagePullPolicy: IfNotPresent
#      volumes:
#        - name: postgres-persistence
#          persistentVolumeClaim:
#            claimName: postgres-pvc
#          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    name: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer