server:
  port: 0
spring:
  application:
    name: "sentiment-ai-processor"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384
  cloud:
    function:
      definition: letterToSentiment
    stream:
      bindings:
        letterToSentiment-in-0:
          destination: letters
          group: sentiment-ai-processor
          consumer:
            concurrency: 1
        letterToSentiment-out-0:
          destination: letter-sentiments
#          group: sentiment-ai-processor
          consumer:
            concurrency: 1
      rabbit:
        bindings:
          letterToSentiment-in-0:
            consumer:
#              queueNameGroupOnly: true
#              container-type: stream
              autoBindDlq: true
          letterToSentiment-out-0:
            consumer:
              #              queueNameGroupOnly: true
              #              container-type: stream
              autoBindDlq: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true